version: "3.9"
services:
  siob:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://Sio:SIO2023@DBMongo:27017/SIO?authSource=admin
      - PORT_URI=3000
    depends_on:
      - DBMongo

  DBMongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Sio
      - MONGO_INITDB_ROOT_PASSWORD=SIO2023
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
